### ISSUE TITLE
Script files missing

### ISSUE THREAD

**Issue by anderssandstrom** [icshwi/e3-EthercatMC#2]
@tboegi, 
The script files in m-epics-ethercatmc/startup seems to be missing in makefile and will therefore not be installed into E3 module:
1. EthercatMCAxis.cmd
2. EthercatMCController.cmd
3. ....

Or is this handled in some other way?

Thanks
Anders

**Comment by tboegi** [comment]
Scripts should be there, please see
https://github.com/icshwi/e3-EthercatMC/commit/847751aa110600dd0a495e4a9a95051e29d41513

**Comment by anderssandstrom** [comment]
My issue was related to 3.0.0. I can see now that 3.0.1 was recently released and fixed this issue.
Thanks
